enum TokenType {
    EOF = 1,
    IntegerLiteral,
    FloatLiteral,
    StringLiteral,
    BooleanLiteral,
    NullLiteral,
    Identifier,
    Dot,
    Comma,
    Semicolon,
    Plus,
    Minus,
    Times,
    Slash,
    Modulus,
    Equal,
    EqualEqual,
    NotEqual,
    GreaterThan,
    LessThan,
    GreaterThanEqual,
    LessThanEqual,
    Not,
    ParenthesisOpen,
    ParenthesisClose,
    BraceOpen,
    BraceClose,
    BracketOpen,
    BracketClose,
}

export default TokenType;
